name: "Install dependencies"

inputs:
  pnpmPath:
    required: true
    type: string
  pnpmKeysPrefix:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ inputs.pnpmPath }}
        key: ${{ inputs.pnpmKeysPrefix }}${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ inputs.pnpmKeysPrefix }}

    - name: Installation
      shell: sh
      run: pnpm install
