# name: base

# on: workflow_call

# jobs:
#   setup:
#     runs-on: ubuntu-latest
#     steps:
# - name: Checkout code
#   uses: actions/checkout@v3

# - name: Fetching git
#   run: git fetch

# - name: Set up Node.js
#   uses: actions/setup-node@v3
#   with:
#     node-version: "18.x"

# - uses: pnpm/action-setup@v2
#   name: Install pnpm
#   with:
#     version: 8
#     run_install: false

# - uses: nrwl/nx-set-shas@v3

# - name: Install NX
#   run: pnpm install -g nx

#   # node:
#   #   needs: git
#   #   runs-on: ubuntu-latest
#   #   steps:

#   # pnpm:
#   #   needs: node
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: pnpm/action-setup@v2
#   #       name: Install pnpm
#   #       with:
#   #         run_install: false

#   # nx:
#   #   needs: pnpm
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: nrwl/nx-set-shas@v3

#   #     - name: Install NX
#   #       run: pnpm install -g nx

name: "Setup base"

runs:
  shell: sh
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetching git
      run: git fetch

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - uses: nrwl/nx-set-shas@v3

    - name: Install NX
      run: pnpm install -g nx
    # - uses: docker/setup-buildx-action@v1

    # - uses: docker/login-action@v1
    #   with:
    #     username: ${{inputs.registry_username}}
    #     password: ${{inputs.registry_password}}

    # - uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: user/app:latest
