FROM node:20-alpine AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN pnpm add tsx -g

COPY package.json pnpm-lock.yaml ./
COPY . .


RUN pnpm i
RUN pnpm nx run api:build

COPY apps/api/.env /app/dist/apps/api

CMD pnpm nx run db:migrate:deploy && pnpm nx run db:seed && cd dist/apps/api && node main.js
