# DEV

FROM --platform=linux/amd64 node:18-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update

EXPOSE 8080
WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN npm install -g nx

COPY .gitignore .gitignore

RUN pnpm install
RUN nx build api

CMD nx serve api
