apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  port: ODA4MA==
  access_secret_token_expires_in: ODY0MDAwMDA=
  access_secret_token: cmFuZG9tX3ZhbHVl
  refresh_secret_token_expires_in: NjA0ODAwMDAw
  refresh_secret_token: c3VwZXJfcmFuZG9tX3ZhbHVl
  db_password: cG9zdGdyZXM=
  db_username: cG9zdGdyZXM=
  db_host: cG9zdGdyZXM=
  db_name: bXlkYg==
  db_port: NTQzMg==
