name: Get nx env
description: Get nx env

runs:
  using: "composite"
  steps:
    - uses: nrwl/nx-set-shas@v3

    - name: set NX env
      shell: bash
      run: |
        nxFlags="--base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}"
        echo "nxDiffFlags=$nxFlags" >> $GITHUB_ENV
        echo "affectedApps=$(pnpm nx show projects --affected --json $nxFlags)" >> $GITHUB_ENV
