name: variables

on:
  workflow_call:
    outputs:
      base:
        value: ${{jobs.variables.outputs.base}}
      head:
        value: ${{jobs.variables.outputs.head}}
      flags:
        value: ${{jobs.variables.outputs.flags}}
      pnpmPath:
        value: ${{jobs.variables.outputs.pnpmPath}}
      pnpmKeysPrefix:
        value: ${{jobs.variables.outputs.pnpmKeysPrefix}}

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Base
        uses: ./.github/actions/base-setup

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        id: storePath
        run: |
          echo "storePath=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    outputs:
      base: ${{ env.NX_BASE }}
      head: ${{ env.NX_HEAD }}
      flags: --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      pnpmPath: ${{ steps.storePath.outputs.storePath }}
      pnpmKeysPrefix: ${{ runner.os }}-pnpm-store-
