name: Deploy web

on:
  workflow_call:
    inputs:
      pnpmPath:
        required: true
        type: string
      pnpmKeysPrefix:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SSH keys creation
        run: echo "${{ secrets.WEB_SSH_PRIVATE_KEY }}" | tr -d '\r' > private-keys.pem
      - name: SSH keys access config
        run: chmod 400 private-keys.pem
      - name: SSH EC2
        run: |
          ssh -i private-keys.pem -o "StrictHostKeyChecking no" ${{secrets.WEB_USER_NAME}}@${{secrets.WEB_SSH_HOST}} <<'ENDSSH'
            cd ${{secrets.WEB_PROJECT_ROOT_ROUTE}} &&
            git pull &&
            pnpm i &&
            pnpm nx pm2 web
          ENDSSH
