name: Deploy api

on:
  workflow_call:
    inputs:
      pnpmPath:
        required: true
        type: string
      pnpmKeysPrefix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SSH EC2
        run: |
          echo ${{ secrets.API_SSH_PRIVATE_KEY }} > "private-keys.pem" && chmod 400 "private-keys.pem" &&
          ssh -i "private-keys.pem" ${{secrets.API_USER_NAME}}@${{secrets.API_SSH_HOST}} '
            cd ${{secrets.API_PROJECT_ROOT_ROUTE}} &&
            git pull &&
            pnpm i &&
            pnpm nx pm2 api
            '
