name: deploy

on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      pnpmPath:
        required: true
        type: string
      pnpmKeysPrefix:
        required: true
        type: string

jobs:
  defineAffectedApps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/base-setup

      - uses: ./.github/actions/install-dependencies
        with:
          pnpmKeysPrefix: ${{inputs.pnpmKeysPrefix}}
          pnpmPath: ${{inputs.pnpmPath}}

      - name: Getting affected apps
        id: affected
        run: |
          echo "affectedApps=$(nx show projects --affected --json ${{ inputs.flags }} }})" >> $GITHUB_OUTPUT
    outputs:
      affectedApps: ${{ steps.affected.outputs.affectedApps }}

  deployWeb:
    needs: defineAffectedApps
    if: contains(needs.defineAffectedApps.outputs.affectedApps, 'web')
    uses: ./.github/workflows/web-deploy.yml
    secrets: inherit
    with:
      pnpmKeysPrefix: ${{inputs.pnpmKeysPrefix}}
      pnpmPath: ${{inputs.pnpmPath}}

  deployApi:
    needs: defineAffectedApps
    if: contains(needs.defineAffectedApps.outputs.affectedApps, 'api')
    uses: ./.github/workflows/api-deploy.yml
    secrets: inherit
    with:
      pnpmKeysPrefix: ${{inputs.pnpmKeysPrefix}}
      pnpmPath: ${{inputs.pnpmPath}}
