name: deploy

on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      pnpmPath:
        required: true
        type: string
      pnpmKeysPrefix:
        required: true
        type: string

jobs:
  defineAffectedApps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/base-setup

      - uses: ./.github/actions/install-dependencies
        with:
          pnpmKeysPrefix: ${{inputs.pnpmKeysPrefix}}
          pnpmPath: ${{inputs.pnpmPath}}

      - name: Getting affected apps
        id: affected
        run: |
          echo "affectedApps=$(nx show projects --affected --json ${{ inputs.flags }} }})" >> $GITHUB_OUTPUT
    outputs:
      affectedApps: ${{ steps.affected.outputs.affectedApps }}

  deploy:
    needs: defineAffectedApps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [web, api]

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Access Variable
      #   run: |
      #     echo "${{ needs.defineAffectedApps.outputs.affectedApps }}"

      - name: Build Project
        if: contains(needs.defineAffectedApps.outputs.affectedApps, matrix.project)
        run: echo ${{ matrix.project }}
