name: prod

on:
  push:
    branches:
      - "main"

jobs:
  variables:
    uses: ./.github/workflows/variables.yml
  test:
    needs: variables
    runs-on: ubuntu-latest
    steps:
      - name: Check is CI valid
        run: echo ${{ needs.variables.outputs.flags }}
      - name: Check is CI valid
        run: echo ${{ needs.variables.outputs.pnpmKeysPrefix }}
      - name: Check is CI valid
        run: echo ${{ needs.variables.outputs.pnpmPath }}
  ci:
    needs: variables
    uses: ./.github/workflows/ci.yml
    with:
      flags: ${{needs.variables.outputs.flags}}
      pnpmKeysPrefix: ${{needs.variables.outputs.pnpmKeysPrefix}}
      pnpmPath: ${{needs.variables.outputs.pnpmPath}}
  ciChecker:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check is CI valid
        if: needs.ci.outputs.isPassed != 'true'
        run: exit 1
  deploy:
    needs: [variables, ci, ciChecker]
    uses: ./.github/workflows/deploy.yml
    with:
      pnpmPath: ${{needs.variables.outputs.pnpmPath}}
      pnpmKeysPrefix: ${{needs.variables.outputs.pnpmKeysPrefix}}
