name: prod

on:
  push:
    branches:
      - "main"

jobs:
  variables:
    uses: ./.github/workflows/variables.yml
  ci:
    needs: variables
    uses: ./.github/workflows/ci.yml
    with:
      flags: ${{needs.variables.outputs.flags}}
      pnpmKeysPrefix: ${{needs.variables.outputs.pnpmKeysPrefix}}
      pnpmPath: ${{needs.variables.outputs.pnpmPath}}
  deployReadyChecker:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check is CI valid
        if: needs.ci.outputs.isPassed != 'true'
        run: exit 1
  deploy:
    uses: ./.github/workflows/deploy.yml
