name: variables

on:
  workflow_call:
    outputs:
      base:
        value: ${{jobs.variables.outputs.base}}
      head:
        value: ${{jobs.variables.outputs.head}}
      flags:
        value: ${{jobs.variables.outputs.flags}}
      pnpmPath:
        value: ${{jobs.variables.outputs.pnpmPath}}
      pnpmKeysPrefix:
        value: ${{jobs.variables.outputs.pnpmKeysPrefix}}

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Base
        uses: ./.github/actions/base-setup

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Getting head
        id: head
        run: |
          echo "head=HEAD" >> $GITHUB_OUTPUT

      - name: Getting base
        id: base
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "base=origin/$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "base=origin/$(echo $GITHUB_BASE_REF)" >> $GITHUB_OUTPUT
          else
            echo "base=origin/main" >> $GITHUB_OUTPUT
          fi

      - name: Get pnpm store directory
        shell: bash
        id: storePath
        run: |
          echo "storePath=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo ${{ github.event_name == 'push' && '' || format('--base={0} --head={1}', steps.base.outputs.base, steps.head.outputs.head) }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo ${{ github.event_name }}

    outputs:
      base: ${{ steps.base.outputs.base }}
      head: ${{ steps.base.outputs.head }}
      flags: ${{ github.event_name == 'push' && '' || format('--base={0} --head={1}', steps.base.outputs.base, steps.head.outputs.head) }}
      pnpmPath: ${{ steps.storePath.outputs.storePath }}
      pnpmKeysPrefix: ${{ runner.os }}-pnpm-store-
